logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:h2:~/testDB;AUTO_SERVER=TRUE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true